language: r
r:
  - 3.1
##  - release
  - devel

sudo: false

cache: packages

os:
  - linux
##  - osx

## dist: trusty

install:
  - export OMP_NUM_THREADS=2
  - wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.12.linux.bin.tar.gz
  - wget https://cran.r-project.org/src/contrib/Archive/roxygen2/roxygen2_5.0.1.tar.gz
  - tar zxf doxygen-1.8.12.linux.bin.tar.gz
  - export PATH=`pwd`/doxygen-1.8.12/bin:$PATH
  - doxygen -v
  - Rscript -e 'pkg <- c("RcppEigen", "numDeriv", "parallel", "knitr", "bookdown", "rsvg"); if(!all(pkg%in%installed.packages()))install.packages(pkg)'
  - Rscript -e 'problemPkg <- "roxygen2_5.0.1.tar.gz"; pkg <- c("roxygen2"); if(!all(pkg%in%installed.packages()))install.packages(problemPkg, repos=NULL)'

script:
  - mkdir ~/.R
  - echo "CXX = g++ -Wall -pedantic -Werror" > ~/.R/Makevars
  - make cran-version
  - make cran-check
  - make install
  - echo "library(TMB);precompile();runExample(all=TRUE)" | R --slave
  - make test
  - make doxygen
  - ./bin/deploy.sh

notifications:
  email:
    on_success: never
    on_failure: never

addons:
  apt:
    packages:
##      - doxygen
      - pandoc
      - graphviz
      - librsvg2-dev

env:
  global:
  - ENCRYPTION_LABEL: "52ee1037b843"
  - COMMIT_AUTHOR_EMAIL: "kaskr@dtu.dk"
